name: svgaplayer_flutter
description: The SVGAPlayer implementation of Flutter using CustomPainter.
version: 2.2.0
homepage: https://github.com/yyued/SVGAPlayer-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  protobuf: ^3.1.0
  http: ^1.1.0
  path_drawing: ^1.0.1
  archive: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
